"""Create table Notify

Revision ID: 5faefe29817a
Revises: 
Create Date: 2024-10-24 21:22:49.266963

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5faefe29817a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("notify_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("message", sa.String(length=1024), nullable=False),
        sa.Column("recipient", sa.JSON(), nullable=True),
        sa.Column("delay", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("notify_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification")
    # ### end Alembic commands ###
