"""one column address

Revision ID: 64becec85f27
Revises: fefb6f2d8e37
Create Date: 2024-10-26 13:09:13.868488

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64becec85f27"
down_revision: Union[str, None] = "fefb6f2d8e37"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("logs", sa.Column("address", sa.String(length=50), nullable=True))
    op.drop_column("logs", "email")
    op.drop_column("logs", "telegram")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "logs",
        sa.Column("telegram", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.add_column(
        "logs",
        sa.Column("email", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    )
    op.drop_column("logs", "address")
    # ### end Alembic commands ###
