"""create logs

Revision ID: aded00407171
Revises: 5faefe29817a
Create Date: 2024-10-26 12:28:33.954955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aded00407171"
down_revision: Union[str, None] = "5faefe29817a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("logs_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.Column("telegram", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("logs_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs")
    # ### end Alembic commands ###
