"""add column sent

Revision ID: fefb6f2d8e37
Revises: aded00407171
Create Date: 2024-10-26 12:37:17.804855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fefb6f2d8e37"
down_revision: Union[str, None] = "aded00407171"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("logs", sa.Column("sent", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("logs", "sent")
    # ### end Alembic commands ###
